[defaults]
    umask = "0022"

[template]
    extension = "tmpl"

[merge]
    command = "vimdiff"

[git]
    autoCommit = true
    autoPush = false

[data]
    prompt_style = "powerlevel10k" # atau "spaceship"
    p10k_style = "neon"            # atau "minimal"
